### ISSUE TITLE
Add a check for the correct robots.txt content

### ISSUE THREAD

**Issue by pmac** [mozmeao/www-site-checker#144]
We recently had an issue that caused our robots.txt URL to return the wrong content. We should keep an automated eye on this as it's very important that it be right.

**Comment by stevejalim** [comment]
Note (to self): this would slot in well as a small standalone script that gets called on its own schedule, rather than shoehorning the code into the main spidering thing, which isn't a good fit for a single-URL content check

**Comment by pmac** [comment]
Maybe it'd be good enough to have it be a check done during deployments?

**Comment by robhudson** [comment]
> Maybe it'd be good enough to have it be a check done during deployments?

I like this approach. We do have some post deploy checks already set up, perhaps it could fit somewhere in there? I believe those are more focused on front-end selenium type tests?

**Comment by pmac** [comment]
it could go in the headless tests. those tend to just be regular requests. and we test redirects during all of that as well.

**Comment by stevejalim** [comment]
Yeah, headless/live-server-request tests would be a good fit - they'd catch
it straight after deploy vs some point in the next X hours for a scheduled
check

**Comment by pmac** [comment]
True. I was initially thinking scheduled since, at least this time, it changed based on a change to the CDN and thus would likely have been caught sooner by something that runs daily rather than just after deployments, but it's probably close enough either way.

**Comment by stevejalim** [comment]
Support added in 042adee03816ad42d76050b109d66a820d12ea13
