### ISSUE TITLE
Add a check that the lang code for each CDN-served page is stable/consistent 

### ISSUE THREAD

**Issue by stevejalim** [mozmeao/www-site-checker#168]
## Context

We had an issue where some CDN work resulted in the CDN serving cached content to for a mismatching locale/geographical region.

To help us be sure that the CDN definitely varies on things we want to it vary on (eg geographic location), and doesn't vary on things it shouldn't vary on, we should add a check that all the pages pulled down from the CDN in the main run all have the same country code in their markup.

### Notes
* Given the run is split across ~8 separate batches, we could either check for consistency within the batch, or ideally check both within each batch and (via an artefact emitted by each batch) across batches too

## Success criteria

- [x] The main CDN checks ensure the same `data-country-code` attr of the root `html` node is consistent across ALL pages checked, regardless of locale
- [x] Mismatches trigger Slack message and open an Issue

**Comment by pmac** [comment]
locale and country code are not corelated at all and should not affect each other. I'd say just pick one, it shouldn't matter which.

**Comment by stevejalim** [comment]
Done
